name: Build Ubuntu executable

on:
  release:
    types: [published]   # Run when a release is published

permissions:
  contents: write # Allow writing to contents for attaching artifacts to releases

jobs:

  build-ubuntu-exe:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version-file: "pyproject.toml"

      - name: Install uv
        uses: astral-sh/setup-uv@08807647e7069bb48b6ef5acd8ec9567f424441b # v8.1.0

      - name: Install dependencies
        run: |
          uv sync --group dev

      - name: Build exe with PyInstaller
        run: |
          uv run pyinstaller ferroci_analyzer_uv.spec

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ubuntu-exe
          path: dist/FerrociAnalyzerUV

      - name: Attach exe to release
        uses: softprops/action-gh-release@v2
        if: github.event_name == 'release'
        with:
          files: dist/FerrociAnalyzerUV
